name: Saweria Listener
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Memungkinkan kamu menjalankan manual

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install saweria-api axios
      - run: node index.js
        env:
          SAWERIA_STREAM_KEY: ${{ secrets.SAWERIA_STREAM_KEY }}
